### ISSUE TITLE
oddly shaped area with lighter gray backround

### ISSUE THREAD

**Issue by andreasn** [abrt/gnome-abrt#116]
The background color of each report has 2 different kinds of grays. The one in the Report area is a lighter color than the rest of the application.

![screenshot from 2015-03-29 03-58-58](https://cloud.githubusercontent.com/assets/209895/6883821/c332c90c-d5c8-11e4-92c5-da578b844433.png)

**Comment by rluzynski** [comment]
Those lighter gray areas are no longer visible but there is a strange thing that those areas are (optionally) scrollable. Probably there is no reason for this (more precisely: probably there is no reason for these small widgets to have their own scrollbars). @jfilak, what is the largest amount of text you expect to be displayed in `*_links` and `*_problem_messages`? Can it be virtually unlimited? Can we just remove the scrollbars and expect that the contents will still fit into any screen, including 800x600, or should we make whole (or almost whole) right panel scrollable?

**Comment by jfilak** [comment]
The number of displayed links should not be greater than 5 but there is not any upper limit. The same apply to the "bottom" message.

**Comment by rluzynski** [comment]
I don't yet request a pull but please review my branch and check if this is what you want or not. It seems that there are really many rows changed but 90% of the changes are formatting so I recommend viewing a diff with spaces ignored. Here is what has really been changed:

* two scrolled windows (lighter gray area) have been removed: `gsw_links` and `gsw_problem_messages`;
* instead of them (almost) whole right panel is inside a new scrolled window;
* the Details button is not inside the scrolled window so it is always visible.

I'm afraid of assuming that we will always have enough vertical space to display any number of links and any number of details message rows and that the vertical scroll bars will never be needed. But please note that the scroll bar will appear only when it is necessary. It will not appear always so most users probably will not notice that it is available. I hope that those who notice it will like it.

Will the screenshots help you review?

**Comment by jfilak** [comment]
@rluzynski Good job! I generated a random crash, added several lines to the file 'reported_to', created the file 'not-reportable'  and opened the problem in gnome-abrt and was shocked how terrible the window looks without your patch. The patch makes the window polished and well integrated. No need to open a pull request, I have pulled your repository to my local repository so I can push the commit if you don't mind.

**Comment by rluzynski** [comment]
Of course I don't mind but I'd like to hear an opinion from the designers, I mean from @allanday, and if not then maybe from @andreasn or Jakub Steiner. Or at least wait a little before we assume that if they don't say anything then they just accept it.

**Comment by jfilak** [comment]
@rluzynski I have pushed the commit to the master. Thank you!
