### ISSUE TITLE
Avoid using ABRT in UI

### ISSUE THREAD

**Issue by mcatanzaro** [abrt/gnome-abrt#127]
The word "ABRT" appears in several places throughout the UI. What's an ABRT? I think this string can almost always be replaced with "problem reporting" (ideally) or "automatic bug reporting tool" when that's not possible.

**Comment by rluzynski** [comment]
I have grepped the source code and I hope these are all occurrences of the word "ABRT" in the UI:

```python
"_ABRT Configuration"                   # in the menu
"_Report problem with ABRT"             # in the menu
"ABRT"                                  # the program name in the About box
"ABRT Team"                             # the Author in the About box
"Open a dialog with ABRT configuration" # a doc string, in module.c, not translated
"A problem with ABRT"                   # the title of the report of the problem in ABRT
"ABRT Manual"                           # the title of the man page
```

"Problem Reporting" sound like a good replacement for "ABRT" but I don't think it should be just replaced automatically. For example "Report problem with Problem Reporting" sounds odd to me. I think that "ABRT Team" in the About box should be left unchanged because it looks like a proper name. The text in the `module.c` should also be left unchanged because it is not a part of the UI and is not translated (or maybe it is? Jakub?)

We need some hints, preferably from English native speakers, how to reword these messages.

**Comment by allanday** [comment]
> "_ABRT Configuration"                   # in the menu

"Preferences"

> "_Report problem with ABRT"             # in the menu

This really shouldn't exist. That's why it sounds strange - you've got problem reporting in your problem reporting. Best I can think  of would be:

"Report a Problem with this Application"

> "ABRT"                                  # the program name in the About box

Fine to leave.

> "ABRT Team"                             # the Author in the About box

Fine to leave.

> "Open a dialog with ABRT configuration" # a doc string, in module.c, not translated

Sounds terrible. I can't advise without knowing where it is used.

> "A problem with ABRT"                   # the title of the report of the problem in ABRT

"A problem with problem reporting" ?

Don't really care that much about this.

> "ABRT Manual"                           # the title of the man page

Fine to leave.

**Comment by jfilak** [comment]
The `module.c` file contains Python bindings for C functions from abrt-lib and libreport. Those strings are not displayed to users, those strings are exported method descriptions.

> "Open a dialog with ABRT configuration" # a doc string, in module.c, not translated

No need for translation and no need for making it user friendly.

**Comment by rluzynski** [comment]
Allan,

Thank you for your response.

> >   "_ABRT Configuration" # in the menu
> 
> "Preferences"

Sorry, no, "Preferences" already exist:

![gnome-abrt-appmenu](https://cloud.githubusercontent.com/assets/11563230/10860303/9993a998-7f66-11e5-90b6-0d6a2f5e87bc.png)

I may be wrong but I guess that the "Preferences" apply to gnome-abrt (the GUI frontend) while the "ABRT Configuration" applies to abrt (the backend).

> >    "ABRT" # the program name in the About box
> 
> Fine to leave.

Are you sure? I thought that this was the most obvious occurrence of ABRT to be replaced with "Problem Reporting":
![gnome-abrt-about](https://cloud.githubusercontent.com/assets/11563230/10860378/691ba3b4-7f67-11e5-8ede-6d1935494416.png)

> >   "ABRT Manual" # the title of the man page
> 
> Fine to leave.

I thought it could be replaced with "Problem Reporting Manual" but that's a minor issue. I think we can assume that the people reading man would not be scared with the word ABRT.

**Comment by allanday** [comment]
> "_ABRT Configuration" # in the menu
> "Preferences"
> Sorry, no, "Preferences" already exist:

If you want to improve the labels, you could have "foo Preferences" and "bar Preferences", where foo and bar are meaningful distinctions to the user (if such a thing can be found).

But really, having two preferences dialogs is pretty broken. They contain some of the worst UI I've ever seen, and should probably be completely removed.

> "ABRT" # the program name in the About box
> Fine to leave.
> Are you sure? I thought that this was the most obvious occurrence of ABRT to be replaced with "Problem Reporting":

Yeah, I might have been wrong there. Sticking with a consistent app name is better.

> "ABRT Manual" # the title of the man page
> Fine to leave.
> I thought it could be replaced with "Problem Reporting Manual" but that's a minor issue. I think we can assume that the people reading man would not be scared with the word ABRT.

If you're reading the man page, you are probably a technical user and have accessed it through the command line. At that point I think we can assume that the user is familiar with the term abrt.
