### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by AsciiWolf** [abrt/gnome-abrt#183]
Please, consider releasing a new version of gnome-abrt. The last release was in October 2016 and there were some commits (mostly translation-related) since then.

P.S. Feel free to update the Czech translation before releasing a new version. I have fixed some typos and other issues.
P.P.S. It looks like the "Reading other users' problems requires authentication" string is not marked for translation.

**Comment by rluzynski** [comment]
The last downstream release was in July 2017 and it included patches for all unreleased upstream commits. Why do you care about an upstream release more than a downstream release? Are you using gnome-abrt outside of Fedora? If yes, please explain.

> P.S. Feel free to update the Czech translation before releasing a new version. I have fixed some typos and other issues.

This sounds reasonable but we must find a balance between "release only when we think we have made a sufficient progress in the source code" and "release whenever anything changes in Zanata".

> P.P.S. It looks like the "Reading other users' problems requires authentication" string is not marked for translation.

True but I'm afraid it's a part of the [abrt](https://github.com/abrt/abrt) project rather than gnome-abrt.
