### ISSUE TITLE
I'm failing to understand what is the use of this application if it never works?

### ISSUE THREAD

**Issue by IllyaYalovyy** [abrt/gnome-abrt#344]
I was trying to submit multiple reports from fedora (36 ... 37). It never succeeds. It always wails with some rediculous reason. 
Network issues, cannot create dump, you name it. 

I just wanted to share my frustration. May be I'm wrong, but in order to be useful an app such as this one, should "just work".

**Comment by msrb** [comment]
Hey @IllyaYalovyy 

Thank you for reaching out. Indeed, versions before 2.16.0 were relying on a retrace sever, which was quite unstable and the results were often a crapshoot. However, version 2.16.0 (since f38+) switched to [debuginfod](https://sourceware.org/elfutils/Debuginfod.html) and the experience should be much better now.

If you still encounter the same problems on f38+, please let us know ;)
