### ISSUE TITLE
Grid align content in details pane

### ISSUE THREAD

**Issue by allanday** [abrt/gnome-abrt#98]
![abrt-grid-align](https://cloud.githubusercontent.com/assets/213068/5455943/42a15a8e-8540-11e4-8f77-63df8f571874.png)
Reducing the number of alignment points will make the pane look tidier and easier to read. A key feature of this is to align the list columns to the icon and heading above, and to move the status message text to the left.

Mockup attached.

**Comment by rluzynski** [comment]
@allanday, please specify the size of the paddings/margins:
* top,
* left,
* right,
* bottom (under the **Details** button, probably should be left unchanged),
* below the icon and heading,
* below the list of properties and values,
* below the long status string (probably this one should be left unchanged).

Should all these paddings have the same size?

**Comment by rluzynski** [comment]
I got no response from Allan but it turned out to be no problem. Left and top margins are not changed, they are 24 and 32, respectively. The right margin was 0 which was the cause of issue #129, changed to 24. The padding between the subblocks (under the icon and between properties/values and the status string) has no effect because these subblocks usually don't adjoin but I have inserted an explicit additional margin 12px to make sure the distance is retained even if a user shrinks the main window to an incredibly small size.

The diff may look huge but it will not be so huge if you choose a diff option ignoring spaces. Most of the changes are due to the formatting.
